config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :email_downcase
  validates :name, presence: true, length: {maximum: Settings.max_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.max_mail},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: Settings.min_pass}
  has_secure_password
  class << self
      byebug
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  private
  def email_downcase
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  attr_reader :user
  def new
  end
  def create
    user = User.find_by email: params_session[:email].downcase
    if user && user.authenticate(params_session[:password])
      login_success user
    else
      login_false user
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  private
  def login_success user
    log_in user
    params[:session][:remember_me] == "1" ? remember(user) : forget(user)
    redirect_to user
  end

  def login_false user
    flash.now[:danger] = t ".danger"
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t(".success")
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end
  
  private

  attr_reader :user
 
  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t(".danger")
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = I18n.t "static_page.base_title"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def params_session
    params[:session]
  end

  private

  def forget user
    user.forget
    cookies.delete :user_id 
    cookies.delete :remember_token
  end
  
  def cookies_permanent
    cookies.permanent
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t (".t1") %><a href="http://www.railstutorial.org/" ><%= t(".t2") %></a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to  t(".t3"), about_path %></li>
      <li><%= link_to  t(".t4"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t(".t5") %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".t1"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".t2"), root_path %></li>
        <li><%= link_to t(".t3"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".t5"), "#" %></li>
          <li class="dropdown">
            <a link_to "#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(".t9") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".t6"), current_user %></li>
              <li><%= link_to t(".t7"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".t8"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".t4"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1><%= t(".t1") %></h1>
<p>
  <%= t(".t2") %> <a href="http://www.railstutorial.org/">
  <em><%= t(".t3") %></em></a> <%= t(".t4") %>
  <a href="http://www.railstutorial.org/book"><%= t(".t5") %></a> <%= t(".t6") %>
  <a href="http://screencasts.railstutorial.org/"><%= t(".t7") %></a>
  <%= t(".t8") %>
  <a href="http://rubyonrails.org/"><%= t(".t9") %></a>.
  <%= t(".t10") %>
</p>

app/views/static_pages/contact.html.erb
<% provide:title, t(".t1") %>
<h1><%= t(".t1") %></h1>
<p>
  <%= t(".t2") %>
  <a href="http://www.railstutorial.org/contact"><%= t(".t3") %></a>.
</p>

app/views/static_pages/help.html.erb
<h1><%= t(".t1") %></h1>
<p>
  <%= t(".t2") %>
  <a href="http://www.railstutorial.org/help"><%= t(".t3") %></a>.
  <%= t(".t4") %>
  <a href="http://www.railstutorial.org/book"><em><%= t(".t5") %></em>
  <%= t(".t6") %></a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".webcome" %></h1>
  <h2>
   <%= t(".t1") %>
    <a href="http://www.railstutorial.org/"><%= t(".t2") %></a>
    <%= t(".t3") %>
  </h2>
  <%= link_to t(".t4"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("kitten.jpg", alt: "Rails logo"),"http://rubyonrails.org/" %>

app/views/users/new.html.erb
<% provide :title, t(".signup") %>
<h1><%= t(".t1") %></h1>  
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t(".t2") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t(".t3"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>